main: net.kunmc.lab.shockwaveplugin.ShockWave
name: ShockWavePlugin
version: "0.1"
api: 1.16.5
api-version: 1.16
authors: [pon52]
description: 衝撃波プラグイン

commands:
  kamehameha:
      description: Get command help
      usage: /<command> help
      permission: op
      permission-message: 権限がありません